sudo: false

language: node_js

node_js:
  - 6
  - 4

cache:
  directories:
    - node_modules

install:
  - npm i -g npm@latest
  - npm install

script:
  - npm run test
  - npm run lint
  - npm run build

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
